name: Use Composite from Another Repo
 
on:
  workflow_dispatch:
 
jobs:
  run-composite:
    runs-on: ubuntu-latest
    permissions: # Grant access to the private repository
      contents: read    
    steps:
      #- name: Authenticate to GitHub
        # uses: actions/checkout@v3
        # with:
        #   token: ${{ secrets.ACCESS_TOKEN }} # Use the PAT configured as a secret    
      - name: Run Composite Action from Another Repo
        uses: prabhu-mns/test/.github/actions@main
